### ISSUE TITLE
Agora.io Support

### ISSUE THREAD

**Issue by sm2x** [nordeck/matrix-meetings#184]
Can this integration work with Agora.io, if not what it takes to hook Agora instead of the current supported videoconferencing

**Comment by dhenneke** [comment]
The current Jitsi integration uses the [Element-integrated Jitsi widget](https://github.com/vector-im/element-web/blob/33eb055f2428b09bbde3f95e35aeded45cc7ba67/docs/jitsi.md) and is configured in the [`default_events.json`](https://github.com/nordeck/matrix-meetings/blob/main/docs/configuration.md#default_events_config):
https://github.com/nordeck/matrix-meetings/blob/f1578790dbf63ba94b893cbe120e52cbc9438aec/matrix-meetings-bot/conf/default_events.json#L29-L43

You can replace the `Video Conference` with a different one, but you would require an agora version that runs as a widget.

**Comment by nurjinjafar** [comment]
Hello @sm2x, does the comment from @dhenneke solves your issue? if yes, please close the issue or reach out to us here or on our [public Room](https://matrix.to/#/#nordeck:matrix.org)
