### ISSUE TITLE
Meetings Widget missing VTIMEZONE in ICS file for Outlook import

### ISSUE THREAD

**Issue by VincentDettmer** [nordeck/matrix-meetings#196]
**Describe the bug**

A user reported an offset +01:00 in their calendar when downloading the ICS file for a meeting and importing it into their Outlook calendar. Presumably this issue only occured after daylight saving time.

Upon validation and further inspection of the ICS file I added the following lines into the ICS after
```
BEGIN:VCALENDAR
VERSION:2.0
```
:
```
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:STANDARD
DTSTART:16011028T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010325T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
```
The modified ICS now behaves correctly upon import.

Please add the corresponding VTIMEZONE segment into the file.

While browsing the ical-generator repository I could verify the package does support this:
https://github.com/sebbo2002/ical-generator/blob/develop/test/results/generate_04.ics

**Steps To Reproduce**

1. Download ICS file for meeting from meeting widget
2. Import into Outlook 2019 during daylight saving time

**Expected behavior**

Beginning and end of meeting should adjust to daylight saving time, they don't. Meeting appears an hour too late in calendar.

**Environment:**
 - OS: Windows 10
 - Browser: Microsoft Edge

**Comment by Sun-Laura** [comment]
Thanks for mentioning this bug. We will check it and give you an update next week.

**Comment by Sun-Laura** [comment]
As an update for the issue: We are currently checking it and working on high priority on the fix.

**Comment by dhenneke** [comment]
@VincentDettmer #207 should fix this issue. I added some example export files in the PR description. Would you be able to download and import them in your environment? The *.zip file includes a meeting in CEST (1st August) and one in CET (1st November) in an export before and an export after the change. We would be happy to learn from you if the new version would solve the issue.

**Comment by VincentDettmer** [comment]
@dhenneke thank you for the PR. I will coordinate the rollout and testing with my colleagues so we can report back shortly.

**Comment by VincentDettmer** [comment]
@dhenneke we took a look at the PR. Looking good so far. Please push an image to the ghcr container registry so we can simply pull by tag for testing.

**Comment by dhenneke** [comment]
@VincentDettmer We automatically push the latest commit of the PRs into the registry. You can use this tag: `ghcr.io/nordeck/matrix-meetings-widget:6eaa906`.

**Comment by VincentDettmer** [comment]
@dhenneke Ewald rolled out the image in dev and confirmed it working. Thank you very much!
